repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        name: black
        args: [ --check ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.4"
    hooks:
      - id: ruff
        exclude: ^migrations/
        args: [--fix, --exit-non-zero-on-fix]