version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    container_name: postgres
    networks:
      - default

  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}
    volumes:
      - ./rabbitmq/rmq-data:/var/lib/rabbitmq
      - ./rabbitmq/rmq-log:/var/log/rabbitmq
    ports:
      - '${FORWARD_RMQ_PORT:-5672}:5672' # TODO: Delete out ports, add management one
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: rabbitmq
    networks:
      - default

  django:
    build:
      context: ./
      dockerfile: ./docker/local.Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './:/var/www/html/'
    env_file:
      - ./.env
    environment:
      DJANGO_SETTINGS_MODULE: 'config.django.dev'
    depends_on:
      - postgres
    links:
      - postgres
      - rabbitmq
    container_name: django
    networks:
      - default

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '${APP_PORT:-80}:80'
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static/:/var/www/html/app/static/
      - ./app/media/:/var/www/html/app/media/
    depends_on:
      - django
    links:
      - django
    container_name: nginx
    networks:
      - default

networks:
  default:
    driver: bridge