# Generated by Django 4.2 on 2024-03-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_date',
        ),
    ]
