# Generated by Django 4.2 on 2024-03-27 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_promocode_subscription_tariff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tariff",
            options={
                "ordering": ("id", "name", "subscription", "amount", "promocode"),
                "verbose_name": "Tariff",
                "verbose_name_plural": "Tariffs",
            },
        ),
        migrations.AlterField(
            model_name="subscription",
            name="cashback",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_cashback",
                to="subscriptions.cashback",
                verbose_name="Cashback",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_category",
                to="subscriptions.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="promocode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promocode_tariff",
                to="subscriptions.promocode",
                verbose_name="Promocode",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promocode_subscription",
                to="subscriptions.subscription",
                verbose_name="Subscription",
            ),
        ),
        migrations.AlterModelTable(
            name="tariff",
            table="tariffs",
        ),
    ]
