# Generated by Django 4.2 on 2024-03-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0004_alter_tariff_options_alter_subscription_cashback_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tariff",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_tariff",
                to="subscriptions.subscription",
                verbose_name="Subscription",
            ),
        ),
    ]
