# Generated by Django 4.2 on 2024-03-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_alter_tariff_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(unique=True, verbose_name="Name"),
        ),
    ]
