# Generated by Django 4.2 on 2024-03-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="subscription_category",
                to="subscriptions.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="subscription_tariff",
                to="subscriptions.subscription",
                verbose_name="Subscription",
            ),
        ),
    ]
