# Generated by Django 4.2 on 2024-03-30 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0010_clientsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 30, 0, 41, 59, 342448),
                verbose_name="expiration_date",
            ),
        ),
    ]
