# Generated by Django 4.2 on 2024-03-30 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_alter_clientsubscription_expiration_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientsubscription",
            options={
                "ordering": (
                    "id",
                    "client",
                    "subscription",
                    "tariff",
                    "promocode",
                    "expiration_date",
                    "is_active",
                ),
                "verbose_name": "Client subscription",
                "verbose_name_plural": "Client Subscriptions",
            },
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 30, 1, 4, 44, 553847),
                verbose_name="expiration_date",
            ),
        ),
        migrations.AlterModelTable(
            name="clientsubscription",
            table="clients_subscriptions",
        ),
    ]
