# Generated by Django 4.2 on 2024-03-30 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0013_alter_clientsubscription_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 30, 2, 29, 1, 811313),
                verbose_name="expiration_date",
            ),
        ),
    ]
