# Generated by Django 4.2 on 2024-03-31 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0015_alter_clientsubscription_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 30, 3, 0, 39, 835385),
                verbose_name="expiration_date",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="name",
            field=models.CharField(unique=True, verbose_name="Name"),
        ),
    ]
