# Generated by Django 4.2 on 2024-03-31 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0016_alter_clientsubscription_expiration_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="days_amount",
            field=models.PositiveIntegerField(default=30, verbose_name="Days amount"),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 30, 3, 47, 5, 964581),
                verbose_name="expiration_date",
            ),
        ),
    ]
