# Generated by Django 4.2 on 2024-03-31 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0017_tariff_days_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 30, 3, 52, 44, 276014),
                verbose_name="expiration_date",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="days_amount",
            field=models.PositiveIntegerField(
                choices=[
                    ("30", "1 месяц"),
                    ("90", "3 месяца"),
                    ("180", "6 месяцев"),
                    ("360", "12 месяцев"),
                ],
                default="30",
                verbose_name="Days amount",
            ),
        ),
    ]
