# Generated by Django 4.2 on 2024-03-31 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0020_alter_tariff_options_remove_tariff_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 30, 4, 24, 17, 242137),
                verbose_name="expiration_date",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="days_amount",
            field=models.PositiveIntegerField(
                choices=[
                    (30, "1 месяц"),
                    (90, "3 месяца"),
                    (180, "6 месяцев"),
                    (360, "12 месяцев"),
                ],
                default=30,
                verbose_name="Days amount",
            ),
        ),
    ]
