# Generated by Django 4.2 on 2024-03-31 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0021_alter_clientsubscription_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 30, 4, 53, 9, 154708),
                verbose_name="expiration_date",
            ),
        ),
    ]
