# Generated by Django 4.2 on 2024-03-31 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0022_alter_clientsubscription_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 30, 11, 7, 24, 598766),
                verbose_name="expiration_date",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionBenefits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="subscriptions/benefits", verbose_name="Icon"
                    ),
                ),
                ("benefit", models.TextField(verbose_name="Benefit")),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_benefit",
                        to="subscriptions.subscription",
                        verbose_name="Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription benefit",
                "verbose_name_plural": "Subscription benefits",
                "db_table": "subscription_benefits",
                "ordering": ("id",),
            },
        ),
    ]
