# Generated by Django 4.2 on 2024-03-31 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0023_alter_clientsubscription_expiration_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientsubscription",
            name="is_liked",
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_liked",
            field=models.BooleanField(default=False, verbose_name="Is liked"),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 30, 13, 7, 55, 300749),
                verbose_name="expiration_date",
            ),
        ),
    ]
