# Generated by Django 4.2 on 2024-04-01 13:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0025_remove_subscription_is_liked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 5, 1, 16, 13, 36, 114515),
                verbose_name="expiration_date",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionbenefits",
            name="icon",
            field=models.FileField(
                upload_to="subscriptions/benefits",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png", "svg"]
                    )
                ],
                verbose_name="Icon",
            ),
        ),
    ]
