# Generated by Django 4.2 on 2024-04-03 17:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0027_subscription_popularity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashback",
            name="amount",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(99.9),
                ],
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 5, 3, 20, 0, 48, 461168),
                verbose_name="expiration_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashback",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gte", 1.0), ("amount__lte", 99.9)),
                name="min_max_range",
            ),
        ),
    ]
