# Generated by Django 4.2 on 2024-04-03 17:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0028_alter_cashback_amount_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cashback",
            name="min_max_range",
        ),
        migrations.AlterField(
            model_name="cashback",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 5, 3, 20, 2, 36, 420305),
                verbose_name="expiration_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashback",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gte", 1), ("amount__lte", 99)),
                name="min_max_range",
            ),
        ),
    ]
