# Generated by Django 4.2 on 2024-04-03 18:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0029_remove_cashback_min_max_range_alter_cashback_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 5, 3, 21, 15, 50, 480493),
                verbose_name="expiration_date",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Amount",
            ),
        ),
    ]
