# Generated by Django 4.2 on 2024-04-04 18:05

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0031_alter_clientsubscription_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscription',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 4, 21, 5, 29, 962197), verbose_name='expiration_date'),
        ),
        migrations.CreateModel(
            name='ClientCashbackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount')),
                ('status', models.CharField(choices=[('cancelled', 'Отменен'), ('pending', 'Ожидание'), ('credited', 'Начислен')], default='pending', verbose_name='Cashback status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_cashback_history', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client cashback history',
                'verbose_name_plural': 'Client cashback histories',
                'db_table': 'client_cashback_history',
                'ordering': ('id', 'amount', 'client', 'status'),
            },
        ),
    ]
