# Generated by Django 4.2 on 2024-04-07 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0033_clientcashbackhistory_client_subscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="conditions",
            field=models.TextField(blank=True, null=True, verbose_name="Conditions"),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2024, 5, 7, 13, 38, 52, 335050),
                verbose_name="expiration_date",
            ),
        ),
    ]
